services:
  postgres-test:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mytestdatabase
    ports:
      - "5432:5432"
      - "5433:5433"
    volumes:
      - pgdata:/var/lib/postgresql/data
    user: "postgres"
    # healthcheck:
    #   test: pg_isready -U postgres -d mytestdatabase
    #   interval: 5s
    #   timeout: 3s
    #   retries: 3

volumes:
  pgdata:
