version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=secret
      - DB_NAME=mydatabase
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for-it.sh", "postgres:5432", "--", "/app/main"]

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  migrations:
    image: golang:1.23.0-alpine
    command: ["migrate", "-path", "/migrations", "-database", "postgres://postgres:secret@postgres:5432/mydatabase?sslmode=disable", "up"]
    volumes:
      - ./migrations:/migrations
    depends_on:
      - postgres

volumes:
  pgdata:
